// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/disc": {
            "post": {
                "description": "Add disc",
                "consumes": [
                    "application/json"
                ],
                "summary": "Add disc",
                "parameters": [
                    {
                        "description": "Disc data",
                        "name": "disc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Disc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/discs": {
            "get": {
                "description": "Get all discs",
                "summary": "Get all discs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Disc"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Disc": {
            "type": "object",
            "properties": {
                "diameter": {
                    "$ref": "#/definitions/models.Measurement"
                },
                "distributor": {
                    "type": "string"
                },
                "fade": {
                    "type": "integer"
                },
                "glide": {
                    "type": "integer"
                },
                "height": {
                    "$ref": "#/definitions/models.Measurement"
                },
                "id": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "maxWeight": {
                    "$ref": "#/definitions/models.Measurement"
                },
                "name": {
                    "type": "string"
                },
                "plasticGrades": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "primaryUse": {
                    "type": "string"
                },
                "rimDepth": {
                    "$ref": "#/definitions/models.Measurement"
                },
                "speed": {
                    "type": "integer"
                },
                "stability": {
                    "type": "string"
                },
                "turn": {
                    "type": "integer"
                }
            }
        },
        "models.Measurement": {
            "type": "object",
            "properties": {
                "unit": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Disc Golf API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
