basePath: /
definitions:
  models.Disc:
    properties:
      diameter:
        $ref: '#/definitions/models.Measurement'
      distributor:
        type: string
      fade:
        type: integer
      glide:
        type: integer
      height:
        $ref: '#/definitions/models.Measurement'
      id:
        type: integer
      maxWeight:
        $ref: '#/definitions/models.Measurement'
      name:
        type: string
      plasticGrades:
        items:
          type: string
        type: array
      primaryUse:
        type: string
      rimDepth:
        $ref: '#/definitions/models.Measurement'
      speed:
        type: integer
      stability:
        type: string
      turn:
        type: integer
    type: object
  models.Measurement:
    properties:
      unit:
        type: string
      value:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  title: Disc Golf API
  version: 0.0.0
paths:
  /discs:
    get:
      description: Get all discs
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Disc'
            type: array
      summary: Get all discs
  /health-check:
    get:
      description: Get API health status
      responses:
        "200":
          description: ""
      summary: Get status of server
swagger: "2.0"
