basePath: /
definitions:
  models.Disc:
    properties:
      diameter:
        $ref: '#/definitions/models.Measurement'
      distributor:
        type: string
      fade:
        type: integer
      glide:
        type: integer
      height:
        $ref: '#/definitions/models.Measurement'
      id:
        type: integer
      link:
        type: string
      maxWeight:
        $ref: '#/definitions/models.Measurement'
      name:
        type: string
      plasticGrades:
        items:
          type: string
        type: array
      primaryUse:
        type: string
      rimDepth:
        $ref: '#/definitions/models.Measurement'
      speed:
        type: integer
      stability:
        type: string
      turn:
        type: integer
    type: object
  models.Measurement:
    properties:
      unit:
        type: string
      value:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  title: Disc Golf API
  version: 0.0.0
paths:
  /disc:
    post:
      consumes:
      - application/json
      description: Add disc
      parameters:
      - description: Disc data
        in: body
        name: disc
        required: true
        schema:
          $ref: '#/definitions/models.Disc'
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Add disc
  /discs:
    get:
      description: Get all discs
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Disc'
            type: array
      summary: Get all discs
swagger: "2.0"
